export const CAR_TYPES = [
  "sedan",
  "suv",
  "crossover",
  "hatchback",
  "pickup",
  "van",
  "coupe",
  "wagon",
  "convertible",
  "minivan",
  "mpv",
  "truck",
] as const;

export const CAR_CATALOG: Record<string, string[]> = {
  Acura: ["ILX", "Integra", "MDX", "RDX", "TLX"],
  "Alfa Romeo": ["Giulia", "Giulietta", "Stelvio", "Tonale"],
  Audi: ["A3", "A4", "A6", "A8", "Q3", "Q5", "Q7", "Q8", "TT"],
  BMW: ["116i", "118i", "316i", "318i", "320i", "520i", "730i", "X1", "X3", "X5", "X6"],
  BYD: ["Atto 3", "Dolphin", "Han", "Qin Plus", "Seagull", "Seal", "Song Plus", "Tang"],
  Cadillac: ["CT4", "CT5", "Escalade", "XT4", "XT5", "XT6"],
  Changan: ["Alsvin", "CS35", "CS55", "CS75", "Eado", "UNI-K", "UNI-T", "Hunter"],
  Chery: ["Arrizo 5", "Arrizo 8", "QQ", "Tiggo 2", "Tiggo 4", "Tiggo 7", "Tiggo 8"],
  Chevrolet: ["Aveo", "Captiva", "Cruze", "Groove", "Malibu", "Silverado", "Spark", "Suburban", "Tahoe", "Traverse"],
  Citroen: ["Berlingo", "C-Elysee", "C3", "C4", "C5 Aircross", "Jumpy"],
  Cupra: ["Ateca", "Born", "Formentor", "Leon"],
  Daihatsu: ["Charade", "Mira", "Sirion", "Terios"],
  Dodge: ["Challenger", "Charger", "Durango", "Ram 1500"],
  Fiat: ["500", "500X", "Doblo", "Ducato", "Egea", "Fiorino", "Linea", "Panda", "Punto", "Tipo"],
  Ford: ["Edge", "Escape", "Everest", "Explorer", "F-150", "Fiesta", "Focus", "Mustang", "Ranger", "Taurus", "Territory"],
  Geely: ["Coolray", "Emgrand", "GX3 Pro", "Monjaro", "Okavango", "Tugella"],
  GMC: ["Acadia", "Canyon", "Sierra", "Terrain", "Yukon"],
  "Great Wall": ["Poer", "Wingle 5", "Wingle 7"],
  Haval: ["H6", "H9", "Jolion", "M6"],
  Honda: ["Accord", "City", "Civic", "CR-V", "HR-V", "Odyssey", "Pilot"],
  Hyundai: ["Accent", "Creta", "Elantra", "H-1", "Kona", "Palisade", "Santa Fe", "Sonata", "Staria", "Tucson", "Veloster"],
  Infiniti: ["Q50", "QX50", "QX55", "QX60", "QX80"],
  Isuzu: ["D-Max", "MU-X", "NLR", "NPR"],
  Iveco: ["Daily"],
  Jac: ["J7", "JS3", "JS4", "JS6", "T8"],
  Jaecoo: ["J7", "J8"],
  Jeep: ["Cherokee", "Compass", "Gladiator", "Grand Cherokee", "Renegade", "Wrangler"],
  Jetour: ["Dashing", "T2", "X70", "X90"],
  Kia: ["Carens", "Carnival", "Cerato", "K3", "K5", "Mohave", "Pegas", "Picanto", "Rio", "Seltos", "Sorento", "Sportage"],
  "Land Rover": ["Defender", "Discovery", "Discovery Sport", "Range Rover Evoque", "Range Rover Sport", "Range Rover Velar"],
  Lexus: ["ES", "GX", "IS", "LS", "LX", "NX", "RX", "UX"],
  Lincoln: ["Aviator", "Corsair", "Navigator", "Nautilus"],
  Mazda: ["2", "3", "6", "BT-50", "CX-3", "CX-30", "CX-5", "CX-9"],
  "Mercedes-Benz": ["A-Class", "C-Class", "CLA", "CLS", "E-Class", "G-Class", "GLA", "GLB", "GLE", "GLS", "S-Class", "Sprinter"],
  MG: ["5", "6", "HS", "RX5", "RX8", "Whale", "ZS"],
  Mini: ["Clubman", "Cooper", "Countryman"],
  Mitsubishi: ["ASX", "Attrage", "Eclipse Cross", "L200", "Mirage", "Montero Sport", "Outlander", "Pajero"],
  Nissan: ["Altima", "Kicks", "Magnite", "Navara", "Patrol", "Pathfinder", "Qashqai", "Sentra", "Sunny", "X-Trail", "Z"],
  Opel: ["Astra", "Combo", "Corsa", "Crossland", "Grandland", "Insignia", "Mokka"],
  Peugeot: ["2008", "208", "3008", "301", "308", "408", "5008", "Partner", "Traveller"],
  Porsche: ["718 Boxster", "718 Cayman", "911", "Cayenne", "Macan", "Panamera", "Taycan"],
  Ram: ["1500", "2500", "3500"],
  Renault: ["Arkana", "Clio", "Duster", "Kangoo", "Koleos", "Logan", "Megane", "Symbol"],
  "Rolls-Royce": ["Cullinan", "Ghost", "Phantom", "Wraith"],
  SEAT: ["Arona", "Ateca", "Ibiza", "Leon", "Toledo"],
  Skoda: ["Fabia", "Kamiq", "Karoq", "Kodiaq", "Octavia", "Superb"],
  Subaru: ["Forester", "Impreza", "Legacy", "Outback", "WRX", "XV"],
  Suzuki: ["Baleno", "Ciaz", "Dzire", "Ertiga", "Jimny", "Swift", "Vitara"],
  Tesla: ["Model 3", "Model S", "Model X", "Model Y"],
  Toyota: ["Avalon", "Camry", "Corolla", "Fortuner", "Hiace", "Hilux", "Innova", "Land Cruiser", "Prado", "RAV4", "Rush", "Yaris"],
  Volkswagen: ["Amarok", "Golf", "Jetta", "Passat", "Polo", "T-Cross", "Tiguan", "Touareg", "Transporter"],
  Volvo: ["S60", "S90", "XC40", "XC60", "XC90"],
};

export const DEFAULT_MAKE = "Toyota";
